-- =========================================================================
-- 0002 — profile API keys + favorites + opportunities
-- Run after 0001 (schema.sql). Idempotent.
-- =========================================================================

-- ---- profiles: add custom API key vault ---------------------------------
-- Stored per-user as JSONB so we don't have to migrate every time a new
-- vendor lands. Frontend writes its own keys; RLS keeps them isolated.
alter table public.profiles
    add column if not exists custom_api_keys jsonb not null default '{}'::jsonb;

alter table public.profiles
    add column if not exists settings jsonb not null default '{}'::jsonb;


-- ---- favorites ----------------------------------------------------------
-- Polymorphic favorites: kind tells you what `ref_id` points at.
--   kind = 'strategy'  → ref_id is a STRATEGIES[].id from strategies.js
--   kind = 'decision'  → ref_id is a decisions.id (uuid-like)
-- `label` is a tiny denormalised cache (name, ticker, rating…) so we can
-- render the favourites list without a JOIN per row.

create table if not exists public.favorites (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    kind        text not null check (kind in ('strategy', 'decision')),
    ref_id      text not null,
    label       jsonb not null default '{}'::jsonb,
    created_at  timestamptz default now(),
    unique (user_id, kind, ref_id)
);

create index if not exists favorites_user_kind_idx
    on public.favorites (user_id, kind, created_at desc);

alter table public.favorites enable row level security;

drop policy if exists "favorites_select_own" on public.favorites;
create policy "favorites_select_own"
    on public.favorites for select using (auth.uid() = user_id);

drop policy if exists "favorites_insert_own" on public.favorites;
create policy "favorites_insert_own"
    on public.favorites for insert with check (auth.uid() = user_id);

drop policy if exists "favorites_delete_own" on public.favorites;
create policy "favorites_delete_own"
    on public.favorites for delete using (auth.uid() = user_id);


-- ---- opportunities ------------------------------------------------------
-- Append-only feed. Backend scanner inserts; users read everything (the feed
-- is shared — there's no per-user filtering at this layer). RLS is permissive
-- on SELECT so anonymous (browsing) users can also see the public feed if
-- you want, while INSERT/DELETE is reserved for the service role.

create table if not exists public.opportunities (
    id           text primary key,
    source       text not null,                  -- 'btc_wick' | 'iv_spike' | 'social_trend' | …
    type         text not null,                  -- short slug
    ticker       text,                            -- nullable for non-symbol events
    severity     text not null default 'info',   -- 'info' | 'watch' | 'high' | 'critical'
    headline     text not null,
    body         text,
    payload      jsonb not null default '{}'::jsonb,
    suggested_strategies text[] default '{}',    -- array of strategy ids
    created_at   timestamptz not null default now(),
    expires_at   timestamptz,
    dismissed_by uuid[] default '{}'             -- users who hit the X (per-user dismiss)
);

create index if not exists opportunities_created_idx
    on public.opportunities (created_at desc);
create index if not exists opportunities_severity_idx
    on public.opportunities (severity, created_at desc);

alter table public.opportunities enable row level security;

drop policy if exists "opportunities_public_read" on public.opportunities;
create policy "opportunities_public_read"
    on public.opportunities for select
    to anon, authenticated
    using (true);

-- Writes are restricted to service-role (the backend scanner). No INSERT
-- policy for anon/authenticated — the missing policy = denied by default.
