-- =========================================================================
-- 0004 — granular per-call usage events (token tracking)
-- Run after 0003. Idempotent.
-- =========================================================================

create table if not exists public.usage_events (
    id            bigint generated by default as identity primary key,
    user_id       uuid not null references auth.users(id) on delete cascade,
    decision_id   text references public.decisions(id) on delete set null,
    ts            timestamptz not null default now(),
    kind          text not null check (kind in ('llm_call', 'tool_call')),
    -- llm_call fields
    provider      text,
    model         text,
    tokens_in     int default 0,
    tokens_out    int default 0,
    -- tool_call fields
    tool_name     text
);

create index if not exists usage_events_user_ts_idx
    on public.usage_events (user_id, ts desc);
create index if not exists usage_events_decision_idx
    on public.usage_events (decision_id);
-- Quick aggregate per provider (Profile usage panel)
create index if not exists usage_events_user_provider_idx
    on public.usage_events (user_id, provider, ts desc);

alter table public.usage_events enable row level security;

drop policy if exists "usage_events_select_own" on public.usage_events;
create policy "usage_events_select_own"
    on public.usage_events for select
    using (auth.uid() = user_id);

drop policy if exists "usage_events_insert_own" on public.usage_events;
create policy "usage_events_insert_own"
    on public.usage_events for insert
    with check (auth.uid() = user_id);

drop policy if exists "usage_events_delete_own" on public.usage_events;
create policy "usage_events_delete_own"
    on public.usage_events for delete
    using (auth.uid() = user_id);

-- Convenience: aggregate view for Profile usage panel
create or replace view public.usage_summary as
select user_id,
       provider,
       date_trunc('day', ts) as day,
       count(*) filter (where kind = 'llm_call')   as llm_calls,
       count(*) filter (where kind = 'tool_call')  as tool_calls,
       coalesce(sum(tokens_in), 0)                 as tokens_in,
       coalesce(sum(tokens_out), 0)                as tokens_out
from public.usage_events
group by user_id, provider, day;

grant select on public.usage_summary to authenticated;
